language: generic
sudo: required

# configuration of services
services: 
  - docker

# run test before building the docker file
before_install:
  - docker build -t psnehi/react-test -f ./client/Dockerfile.dev ./client

# create docker file
script:
  - docker run -e CI=true psnehi/react-test npm test -- --coverage

# create docker of each service
after_success:
  - docker build -t psnehi/multi-client ./client
  - docker build -t psnehi/multi-nginx ./nginx
  - docker build -t psnehi/multi-server ./server
  - docker build -t psnehi/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images to the Dockerhub
  - docker push psnehi/multi-client
  - docker push psnehi/multi-nginx
  - docker push psnehi/multi-server 
  - docker push psnehi/multi-worker
  # all images push to the docker hub

deploy: 
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-ap-south-1-748659118671
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
