language: generic
sudo: required

services: 
  - docker

before_install:
  - docker build -t psnehi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true psnehi/react-test npm test -- --coverage

after_success:
  - docker build -t psnehi/multi-client ./client
  - docker build -t psnehi/multi-nginx ./nginx
  - docker build -t psnehi/multi-server ./server
  - docker build -t psnehi/multi-worker ./worker
