version: '3'
services:
  client:
    image: "psnehi/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "psnehi/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
  worker:
    image: "psnehi/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - WDS_SOCKET_PORT=0
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx: 
    image: "psnehi/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
  