version: '3'
services:
  client:
    image: "psnehi/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "psnehi/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
  worker:
    image: "psnehi/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - WDS_SOCKET_PORT=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379    - PGPORT=5432
  nginx: 
    image: "psnehi/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
  
  
  